ehr: str = '/Users/kasra/OneDrive - University of Delaware - o365/UCSF Data/Overall.xlsx'
mri: str = '/Users/kasra/OneDrive - University of Delaware - o365/UCSF Data/HCM_MRI_Database_03022022.xlsx'
ecg: str = 'Data/ECG/ScarECG'
website_ecg: str = 'Data/ECG/WebsiteECG'
muse: str = '/Users/kasra/OneDrive - University of Delaware - o365/UCSF Data/Muse'
pla_annotation: str = 'Data/ECG/ScarECG/PLAAnnotation'
website_pla_annotation: str = 'Data/ECG/WebsiteECG/PLAAnnotation'
fqrs_annotation: str = '/Users/kasra/OneDrive - University of Delaware - o365/UCSF Data/ECG_Talha_Fragmentation.xlsx'
cached_imputed_ehr: str = 'Data/CachedEHR/ehr_df.xlsx'
cached_scar_ecg_meta: str = 'Data/ECG/ScarECG/scar_ecg_meta.xlsx'
website_ecg_meta: str = 'Data/ECG/WebsiteECG/website_ecg_meta.xlsx'
qt_segment_dataset: str = 'Data/Dataset/QTSegment'
cached_qt_segment_dataset: str = 'Data/Dataset/QTSegment/qt_segment_dataset.npy'


